config/routes.rb
Rails.application.routes.draw do

  get '/categories/:id', to:'categories#show', as: 'category'

  get '/artists/:id', to:'artists#show', as: 'artist'
  
  
  root 'home#index'
  get '/home', to:'home#show', as: 'home'
  get '/home/artists/:id', to: 'home#artists'

end

app/models/home.rb
class Home < ActiveRecord::Base
	Filters = ['Activity', 'Artist', 'Genre', 'Mood']
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

 rescue_from RestClient::ResourceNotFound, :with => :resource_not_found

  private

  def resource_not_found
    redirect_to root_path and return
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index

  end

  def show
  	unless RSpotify::Artist.find(params[:id])
  	  flash[:notice] = 'Invalid ID'
	    redirect_to root_path and return
  	else
  	  @artist = RSpotify::Artist.find(params[:id])
  	end
  	
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    
    @category = params[:id] # retrieve project task ID from URI route
  	id = @category.downcase
    choices = ["toplists","mood","party","workout","pop","popculture", "focus", "rock","edm_dance", "chill","dinner", "sleep","hiphop","rnb", "country","folk_americana","metal","soul", "travel" ]
    
    if !choices.include?(id)
      flash[:notice] = 'Invalid Search Parameters'
      redirect_to root_path and return
    else

    RSpotify.authenticate("70c8eb6616be4e849cc7e035e97f99fc", "a45a56959d9447afb84dd8ceb1ee4ece")

    category = RSpotify::Category.find(id) 
    RestClient::ResourceNotFound


    @list = []

    category.playlists.each do |name|
      @list.push(name.name)
    end

    @songs = category.playlists[0].tracks

    end
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def show
 	  category = params[:filter]

 	  if params[:search_value].blank?
 	  	redirect_to root_path and return
 	  else
 	  	value = params[:search_value]
 	  end

 	  case category
      when 'Activity', 'Mood', 'Genre'
 	  	redirect_to category_path(value) and return
 	  when 'Artist'
 	  	@artists = RSpotify::Artist.search(value)

 	  	if !@artists.blank?
 	  	  @artist_id = @artists.first.id
 	  	  redirect_to artist_path(@artist_id) and return
		else
		  flash[:notice] = 'Invalid ID'
 	  	  redirect_to root_path and return
 	  	end

 	  else
 	  	redirect_to root_path and return
 	  end
 	  
	end

	def artists
        id = params[:id]
		artists = RSpotify::Artist.search("#{id}*", limit: 20, market: 'US')
		list = []
		artists.each do |artist|
		   list.push(artist.name)
		end
		render json: list
   end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/application/_html_header.html.erb
<div class="login">
    <button onclick="alert('Hello')" type="button">login</button>
    <button onclick="alert('Hello')" type="button">sign-up</button>
</div>

<div class="header">
 Playlist Curator
</div>

app/views/artists/_album_view.html.erb
<% @artist.albums(country: 'US').each do |album| %>
 <h3><%= album.name %></h3>
 <ul>
   <% album.tracks.each do |track| %>
     <li>
       <%= track.name %>
     </li>
   <% end %>
 </ul>
<% end %>

app/views/artists/_all_view.html.erb
<table>
	<thead>
	  <tr>
	    <th>Title</th>
	    <th>Duration</th>
	    <th>Album</th>
      </tr>
	</thead>

	<tbody>
      <% @artist.albums(country: 'US').each do |album| %>
	  <% album.tracks.each do |track| %>
	  <tr>	        
	    <td>
		  <%= track.name %>
		</td>
		<td>
		  <%= track.duration_ms %> 
		</td>
		<td>
		  <%= album.name %>
		</td>
		
		      
	  </tr>
	  <% end %>
	  <% end %>
	</tbody>
</table> 

app/views/artists/index.html.erb
<!-- app/views/artists/index.html.erb -->

<h1 class="page-header"><%= @artist.name %></h1>
<% @artist.albums(country: 'US').each do |album| %>
 <h3><%= album.name %></h3>
 <ul>
   <% album.tracks.each do |track| %>
     <li>
       <%= track.name %>
     </li>
   <% end %>
 </ul>
<% end %>

app/views/artists/show.html.erb
<!-- app/views/artists/show.html.erb -->
<body>
<div class="page-wrapper"id="content">
  <div class="main supporting" role="main">
	<div class="playlist">
	  <h2><%= @artist.name %></h2>
	  <%= render 'album_view' %>
	</div>

	<footer>
      <a href="https://github.com/UCCS-CS3300-Spring2016/Group3" class="zen-github">Home</a>
	  <a href="http://https://www.spotify.com/" title="Spotify" class="zen-validate-html">Spotify</a>
	  <a href="https://github.com/UCCS-CS3300-Spring2016/Group3" class="zen-github">GitHub</a>
	</footer>
  </div>

  <aside class="sidebar" role="complementary">
		<div class="wrapper">

			<div class="design-selection" id="design-selection">

				<nav role="navigation">
					<ul>
					<li><h3>Group By:</h3></li>
					<li>
						<a href="/221/" class="design-name">Album</a>
					</li>					
					<li>
						<a href="/220/" class="design-name">Genre</a> 
					</li>					
					<li>
						<a href="/219/" class="design-name">None</a>
					</li>	
					</ul>
				</nav>
			</div>

			
	</aside>
</div>
</body>

app/views/categories/index.html.erb
<!-- app/views/artists/index.html.erb -->

<h1 class="page-header">Category List</h1>
 <ul>
   <% RSpotify::Category.list.each do |category|  %>
     <li>
       <%= category %>
     </li>
   <% end %>
 </ul>

app/views/categories/show.html.erb
<!-- app/views/category/show.html.erb -->

<body>
  <div class="page-wrapper"id="content">
    <div class="main supporting" role="main">
      <div class="playlist">
        <h2><%= @category %></h2>
        <table>
          <thead>
            <tr>
              <th>Title</th>
              <th>Artist</th>
              </tr>
          </thead>
          <tbody>
            <% @songs.each do |song| %>
              <tr>
                <td>
                  <%= song.name %>
                </td>
                <td>
                  <%= song.artists[0].name %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        
      </div>

      <footer>
          <a href="https://github.com/UCCS-CS3300-Spring2016/Group3" class="zen-github">Home</a>
        <a href="http://https://www.spotify.com/" title="Spotify" class="zen-validate-html">Spotify</a>
        <a href="https://github.com/UCCS-CS3300-Spring2016/Group3" class="zen-github">GitHub</a>
      </footer>
    </div>

    <aside class="sidebar" role="complementary">
      <div class="wrapper">

        <div class="design-selection" id="design-selection">

          <nav role="navigation">
            <ul>
            <li><h3>Group By:</h3></li>
            <li>
              <a href="/221/" class="design-name">Album</a>
            </li>         
            <li>
              <a href="/220/" class="design-name">Genre</a> 
            </li>         
            <li>
              <a href="/219/" class="design-name">None</a>
            </li> 
            </ul>
          </nav>
        </div>

        
    </aside>
  </div>
</body>

app/views/home/index.html.erb
<!-- app/views/home/index.html.erb -->

<body>
  
  <div id="content">

    <div id="playlist-pick">
    <%= form_tag home_path, :method => "get" do %>
      <h1>Let's Get Started</h1>
      <label for="filter">How do you want to base this playlist?</label>
      <%= select_tag( :filter, options_for_select(Home::Filters), {prompt: 'Filter by...'}) %>
      <%= text_field_tag(:search_value, nil, {placeholder:'Search for...', id: "select-playlist", disabled: false}) %>
      <%= submit_tag 'Generate!', :id => "get-playlist"%>
      <% end %>
    </div>
  </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<!DOCTYPE html>
<html>
  <head>
    <%= render 'html_header' %>
    <%= stylesheet_link_tag 'application' %>
    <%= stylesheet_link_tag 'jquery-ui.min' %>
    <%= stylesheet_link_tag 'jquery-ui.structure.min' %>
    <%= stylesheet_link_tag 'jquery-ui.theme.min' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="main">
      <% if flash[:notice] %>
        <div class="message" id="notice">
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:warning] %>
        <div class="message" id="warning">
          <%= flash[:warning] %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>